[tool.isort]
atomic = true
include_trailing_comma = true
known_first_party = "te"
line_length = 88
multi_line_output = 3

[tool.pytest.ini_options]
markers = [
    "etc_hosts: passes path for etc_hosts fixture",
]

[tool.semantic_release]
version_source = "commit"
commit_subject = "chore: Release version {version}"
commit_message = "Releasing te version {version}"
version_variable = [
    "src/te/version.py:VERSION",
    "docs/conf.py:release",
]
version_pattern = [
    "te.spec:Version:\\s+{version}",
]
branch = "main"
commit = true
tag = true
